deploy/undeploy/offline migration is working

diff --git a/tm/3par/mv b/tm/3par/mv
--- a/tm/3par/mv
+++ b/tm/3par/mv
@@ -75,6 +75,15 @@ fi
 LCM_STATE=`lcm_state`
 
 if [ `is_disk $DST_PATH` -eq 0 ]; then
+    # for PROLOG_RESUME + PROLOG_UNDEPLOY we got nothing to do
+    if [[ "$LCM_STATE" =~ ^(9|31|49|50)$ ]]; then
+        exit 0
+    fi
+    # for EPILOG_STOP + EPILOG_UNDEPLOY we got nothing to do
+    if [[ "$LCM_STATE" =~ ^(10|30|41|42)$ ]]; then
+        exit 0
+    fi
+
     # VM is in unknown state, SRC_HOST probably in failed state
     if [ $LCM_STATE -eq 60 ] || [ $LCM_STATE -eq 61 ]; then
       log "Not moving files from $SRC_HOST in FT mode"
@@ -91,6 +100,7 @@ if [ `is_disk $DST_PATH` -eq 0 ]; then
     TAR_SSH=$(cat <<EOF
     set -e -o pipefail
     
+    # TODO: ssh agent
     $TAR -C $SRC_DS_DIR --sparse -cf - $SRC_VM_DIR | $SSH $DST_HOST '$TAR -C $DST_DIR --sparse -xf -'
     rm -rf $SRC_PATH
 EOF
@@ -138,7 +148,7 @@ done < <(onedatastore show -x $SYS_DSID | $XPATH /DATASTORE/TEMPLATE/NAMING_TYPE
                                                  /DATASTORE/TEMPLATE/PORTALS)
 
 NAMING_TYPE="${XPATH_ELEMENTS[j++]:-$NAMING_TYPE}"
-PORTALS="${XPATH_ELEMENTS[J++]:-$PORTALS}"
+PORTALS="${XPATH_ELEMENTS[j++]:-$PORTALS}"
 
 # Disk os clone, so copy was created
 if [ "$CLONE" = "YES" ]; then
@@ -167,77 +177,83 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
-DST_HOST_3PAR=$(${DRIVER_PATH}/../../datastore/3par/3par.py hostExists -a $API_ENDPOINT -i $IP -s $SECURE -u $USERNAME \
-                                                                        -p $PASSWORD -hs $DST_HOST)
-
-if [ $? -ne 0 ]; then
-  error_message "$DST_HOST_3PAR"
-  exit 1
-fi
 
 # Not persistent and not clone, so this disk can be used by more VMs at the same time
 CAN_UNMAP=1
-if [ "$PERSISTENT" != "YES" ] && [ "$CLONE" == "NO" ]; then
-    # check if disk is in use by other VMs
-    unset i XPATH_ELEMENTS
 
-    while IFS= read -r -d '' element; do
-        XPATH_ELEMENTS[i++]="$element"
-    done < <(oneimage show -x $IMAGE_ID| $XPATH /IMAGE/RUNNING_VMS)
-
-    RUNNING_VMS="${XPATH_ELEMENTS[0]}"
-
-    # image is used, so can't unmap
-    [ "$RUNNING_VMS" != "1" ] && CAN_UNMAP=0
-fi
-
-if [ "$SRC_HOST_3PAR" == "1" ] && [ "$CAN_UNMAP" == "1" ]; then
-    log "Unmapping $WWN from $SRC_HOST"
-
-    # src host in failed state, can not flush disk before unexport
-    if [ $LCM_STATE -ne 60 ] && [ $LCM_STATE -ne 61 ]; then
-        FLUSH_CMD=$(cat <<EOF
-          set -e
-          $(remove_lun "$WWN")
+# for PROLOG_RESUME + PROLOG_UNDEPLOY skip deactivate
+if ! [[ "$LCM_STATE" =~ ^(9|31|49|50)$ ]]; then
+    if [ "$PERSISTENT" != "YES" ] && [ "$CLONE" == "NO" ]; then
+        # check if disk is in use by other VMs
+        unset i XPATH_ELEMENTS
+    
+        while IFS= read -r -d '' element; do
+            XPATH_ELEMENTS[i++]="$element"
+        done < <(oneimage show -x $IMAGE_ID| $XPATH /IMAGE/RUNNING_VMS)
+    
+        RUNNING_VMS="${XPATH_ELEMENTS[0]}"
+    
+        # image is used, so can't unmap
+        [ "$RUNNING_VMS" != "1" ] && CAN_UNMAP=0
+    fi
+    
+    if [ "$SRC_HOST_3PAR" == "1" ] && [ "$CAN_UNMAP" == "1" ]; then
+        log "Unmapping $WWN from $SRC_HOST"
+    
+        # src host in failed state, can not flush disk before unexport
+        if [ $LCM_STATE -ne 60 ] && [ $LCM_STATE -ne 61 ]; then
+            FLUSH_CMD=$(cat <<EOF
+              set -e
+              $(remove_lun "$WWN")
 EOF
 )
-
-        ssh_exec_and_log "$SRC_HOST" "$FLUSH_CMD" \
-            "Error flushing out mapping"
-    fi
-
-    ${DRIVER_PATH}/../../datastore/3par/3par.py unexportVV -a $API_ENDPOINT -i $IP -s $SECURE -u $USERNAME -p $PASSWORD \
-                                                                -n $NAME -hs $SRC_HOST
-
-    if [ $? -ne 0 ]; then
-      error_message "Error unexporting VV"
-      exit 1
-    fi
-
-    ${DRIVER_PATH}/../../datastore/3par/3par.py deleteHost -a $API_ENDPOINT -i $IP -s $SECURE -u $USERNAME -p $PASSWORD \
-                                                                -hs $SRC_HOST
-    if [ $? -eq 0 ]; then
-        ssh_exec_and_log "$DST_HOST" "
-        for PORTAL in $PORTALS; do
-            sudo iscsiadm --mode node -u -p \"\$PORTAL\" || true
-        done
-        "
-    fi
-fi
-
-if [ "$DST_HOST_3PAR" == "0" ]; then
-    DST_HOST_ISCSI_NAME=$($SSH $DST_HOST sudo cat /etc/iscsi/initiatorname.iscsi | awk -F= '{print $2}')
-    ${DRIVER_PATH}/../../datastore/3par/3par.py createHost -a $API_ENDPOINT -i $IP -s $SECURE -u $USERNAME -p $PASSWORD \
-                                                                -hs $DST_HOST -in $DST_HOST_ISCSI_NAME
-    ssh_exec_and_log "$DST_HOST" "
-    for PORTAL in $PORTALS; do
-        if ! sudo iscsiadm -m session -o show | awk '{print \$3}' | grep -q \"\$PORTAL[:,]\"; then
-            sudo iscsiadm -m discovery -t sendtargets -p \"\$PORTAL\"
-            sudo iscsiadm -m node -l all -p \"\$PORTAL\"
+    
+            ssh_exec_and_log "$SRC_HOST" "$FLUSH_CMD" \
+                "Error flushing out mapping"
         fi
-    done
-    "
+    
+        ${DRIVER_PATH}/../../datastore/3par/3par.py unexportVV -a $API_ENDPOINT -i $IP -s $SECURE -u $USERNAME -p $PASSWORD \
+            -n $NAME -hs $SRC_HOST
+    
+        if [ $? -ne 0 ]; then
+          error_message "Error unexporting VV"
+          exit 1
+        fi
+
+        ${DRIVER_PATH}/../../datastore/3par/3par.py deleteHost -a $API_ENDPOINT -i $IP -s $SECURE -u $USERNAME -p $PASSWORD \
+            -hs $SRC_HOST
+    
+        if [ $? -eq 0 ]; then
+            ssh_exec_and_log "$SRC_HOST" "
+            for PORTAL in $PORTALS; do
+                sudo iscsiadm --mode node -u -p \"\$PORTAL\" || true
+            done
+            "
+        fi
+    fi
 fi
+
+# for EPILOG_STOP + EPILOG_UNDEPLOY we got nothing to do
+if [[ "$LCM_STATE" =~ ^(10|30|41|42)$ ]]; then
+    exit 0
+fi
+
+DST_HOST_ISCSI_NAME=$($SSH $DST_HOST sudo cat /etc/iscsi/initiatorname.iscsi | awk -F= '{print $2}')
+DST_HOST_3PAR=$(${DRIVER_PATH}/../../datastore/3par/3par.py createHost -a $API_ENDPOINT -i $IP -s $SECURE -u $USERNAME -p $PASSWORD \
+    -hs $DST_HOST -in $DST_HOST_ISCSI_NAME)
+if [ $? -ne 0 ]; then
+    error_message "$DST_HOST_3PAR"
+    exit 1
+fi
+
+ssh_exec_and_log "$DST_HOST" "
+for PORTAL in $PORTALS; do
+    if ! sudo iscsiadm -m session -o show | awk '{print \$3}' | grep -q \"\$PORTAL[:,]\"; then
+        sudo iscsiadm -m discovery -t sendtargets -p \"\$PORTAL\"
+        sudo iscsiadm -m node -l all -p \"\$PORTAL\"
+    fi
+done
+"
 
 log "Mapping $NAME_WWN to $DST_HOST"
 
